[project]
name = "matrix-caramel-bot"
version = "0.1.0"
description = "A Matrix bot that does silly things, written in Python."
requires-python = ">=3.13"
dependencies = [
    "nio-bot==1.2.0",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ruff>=0.9.4",
]
